### ISSUE TITLE
node 使用14.18.0 安装 一直提示intro.js@^1.3.0.  no matching version found

### ISSUE THREAD

**Issue by liuducms** [NaTieJun/orise-admin#2]
node 使用14.18.0 安装 一直提示intro.js@^1.3.0.  no matching version found

**Comment by NaTieJun** [comment]
无法复现，可能跟网络环境、源有关。

**Comment by NaTieJun** [comment]
可以尝试使用以下方法：
安装新的intro.js版本，最新已经到2.9.0
